2023-09-12 21:01:10,282 - [Winbot] - INFO - Initialized Database!

2023-09-12 21:01:29,122 - [Winbot] - ERROR - list index out of range
Traceback (most recent call last):
  File "C:\Users\soudh\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\soudh\OneDrive\Desktop\my works\programing\APP python project\winbot\events.py", line 17, in onMessage
    await command["callback"](client,message,extra)
  File "C:\Users\soudh\OneDrive\Desktop\my works\programing\APP python project\winbot\plugins\filter.py", line 47, in run
    lol = eee if m.reply_to_message else extracted[1]
IndexError: list index out of range
2023-09-12 21:04:20,320 - [Winbot] - WARNING - Unable to connect due to network issues: timed out
2023-09-12 21:04:31,351 - [Winbot] - WARNING - Unable to connect due to network issues: timed out
2023-09-12 21:05:49,144 - [Winbot] - INFO - 783836937 added new filter (hello) in -1001768994767
